import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Download, FileJson, FileText, Copy, Check, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { useToast } from "@/hooks/use-toast";

interface ExportContent {
  headline: string;
  bodyText: string;
  callToAction: string;
}

interface ExportDialogProps {
  isOpen: boolean;
  onClose: () => void;
  content: ExportContent | null;
  platform: string;
}

export const ExportDialog = ({ isOpen, onClose, content, platform }: ExportDialogProps) => {
  const [copiedFormat, setCopiedFormat] = useState<string | null>(null);
  const { toast } = useToast();

  if (!content) return null;

  const exportData = {
    platform,
    generatedAt: new Date().toISOString(),
    content: {
      headline: content.headline,
      bodyText: content.bodyText,
      callToAction: content.callToAction,
    },
    metadata: {
      generator: "AdCraft AI",
      version: "1.0",
    },
  };

  const jsonContent = JSON.stringify(exportData, null, 2);

  const markdownContent = `# Generated Ad Copy

## Platform
${platform.toUpperCase()}

## Generated At
${new Date().toLocaleString()}

---

## Headline
${content.headline}

## Body Text
${content.bodyText}

## Call to Action
${content.callToAction}

---

*Generated by AdCraft AI*
`;

  const copyToClipboard = async (text: string, format: string) => {
    try {
      await navigator.clipboard.writeText(text);
      setCopiedFormat(format);
      toast({
        title: "Copied!",
        description: `${format.toUpperCase()} content copied to clipboard.`,
      });
      setTimeout(() => setCopiedFormat(null), 2000);
    } catch (error) {
      toast({
        title: "Copy failed",
        description: "Unable to copy to clipboard.",
        variant: "destructive",
      });
    }
  };

  const downloadFile = (content: string, filename: string, mimeType: string) => {
    const blob = new Blob([content], { type: mimeType });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);

    toast({
      title: "Downloaded!",
      description: `File saved as ${filename}`,
    });
  };

  return (
    <Dialog open={isOpen} onOpenChange={onClose}>
      <DialogContent className="max-w-2xl bg-card border-border">
        <DialogHeader>
          <DialogTitle className="text-foreground flex items-center gap-2">
            <Download className="w-5 h-5 text-primary" />
            Export Ad Copy
          </DialogTitle>
        </DialogHeader>

        <div className="space-y-6 py-4">
          {/* JSON Export */}
          <motion.div
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            className="space-y-3"
          >
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-2">
                <FileJson className="w-5 h-5 text-secondary" />
                <h3 className="font-semibold text-foreground">JSON Format</h3>
              </div>
              <div className="flex items-center gap-2">
                <Button
                  variant="outline"
                  size="sm"
                  onClick={() => copyToClipboard(jsonContent, "json")}
                  className="border-border"
                >
                  {copiedFormat === "json" ? (
                    <Check className="w-4 h-4 text-success" />
                  ) : (
                    <Copy className="w-4 h-4" />
                  )}
                  <span className="ml-2">Copy</span>
                </Button>
                <Button
                  size="sm"
                  onClick={() =>
                    downloadFile(jsonContent, `adcraft-${platform}-${Date.now()}.json`, "application/json")
                  }
                  className="bg-secondary text-secondary-foreground hover:bg-secondary/90"
                >
                  <Download className="w-4 h-4 mr-2" />
                  Download
                </Button>
              </div>
            </div>
            <pre className="p-4 rounded-lg bg-muted/50 border border-border text-sm overflow-x-auto max-h-40 overflow-y-auto">
              <code className="text-foreground">{jsonContent}</code>
            </pre>
          </motion.div>

          {/* Markdown Export */}
          <motion.div
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.1 }}
            className="space-y-3"
          >
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-2">
                <FileText className="w-5 h-5 text-primary" />
                <h3 className="font-semibold text-foreground">Markdown Format</h3>
              </div>
              <div className="flex items-center gap-2">
                <Button
                  variant="outline"
                  size="sm"
                  onClick={() => copyToClipboard(markdownContent, "markdown")}
                  className="border-border"
                >
                  {copiedFormat === "markdown" ? (
                    <Check className="w-4 h-4 text-success" />
                  ) : (
                    <Copy className="w-4 h-4" />
                  )}
                  <span className="ml-2">Copy</span>
                </Button>
                <Button
                  size="sm"
                  onClick={() =>
                    downloadFile(markdownContent, `adcraft-${platform}-${Date.now()}.md`, "text/markdown")
                  }
                  className="bg-primary text-primary-foreground hover:bg-primary/90"
                >
                  <Download className="w-4 h-4 mr-2" />
                  Download
                </Button>
              </div>
            </div>
            <pre className="p-4 rounded-lg bg-muted/50 border border-border text-sm overflow-x-auto max-h-40 overflow-y-auto whitespace-pre-wrap">
              <code className="text-foreground">{markdownContent}</code>
            </pre>
          </motion.div>
        </div>
      </DialogContent>
    </Dialog>
  );
};
